FROM haproxy:2.9-alpine

# haproxy.cfg se genera en tiempo de arranque via entrypoint
COPY --chmod=755 haproxy-entrypoint.sh /usr/local/bin/entrypoint.sh
EXPOSE 80
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
